/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FInstanceIdRouteImport } from './routes/f.$instanceId'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated.users'
import { Route as AuthenticatedTripsRouteImport } from './routes/_authenticated.trips'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated.templates'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedPlanningRouteImport } from './routes/_authenticated.planning'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated.inbox'
import { Route as AuthenticatedFormsRouteImport } from './routes/_authenticated.forms'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated.agents'
import { Route as AuthenticatedTripsIndexRouteImport } from './routes/_authenticated.trips.index'
import { Route as AuthenticatedSchoolsIndexRouteImport } from './routes/_authenticated.schools.index'
import { Route as AuthenticatedAgentsIndexRouteImport } from './routes/_authenticated.agents.index'
import { Route as PublicIntakeTypeRouteImport } from './routes/public.intake.$type'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as FormsActivityIdTemplateIdRouteImport } from './routes/forms.$activityId.$templateId'
import { Route as AuthenticatedTripsTripIdRouteImport } from './routes/_authenticated.trips.$tripId'
import { Route as AuthenticatedSchoolsSchoolIdRouteImport } from './routes/_authenticated.schools.$schoolId'
import { Route as AuthenticatedAgentsAgentIdRouteImport } from './routes/_authenticated.agents.$agentId'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPlanningRemindersRouteImport } from './routes/api/public/planning/reminders'
import { Route as AuthenticatedTripsTripIdReportRouteImport } from './routes/_authenticated.trips.$tripId.report'
import { Route as AuthenticatedTripsTripIdActivitiesActivityIdRouteImport } from './routes/_authenticated.trips.$tripId.activities.$activityId'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FInstanceIdRoute = FInstanceIdRouteImport.update({
  id: '/f/$instanceId',
  path: '/f/$instanceId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTripsRoute = AuthenticatedTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlanningRoute = AuthenticatedPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFormsRoute = AuthenticatedFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTripsIndexRoute = AuthenticatedTripsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTripsRoute,
} as any)
const AuthenticatedSchoolsIndexRoute =
  AuthenticatedSchoolsIndexRouteImport.update({
    id: '/schools/',
    path: '/schools/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentsIndexRoute =
  AuthenticatedAgentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAgentsRoute,
  } as any)
const PublicIntakeTypeRoute = PublicIntakeTypeRouteImport.update({
  id: '/public/intake/$type',
  path: '/public/intake/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsActivityIdTemplateIdRoute =
  FormsActivityIdTemplateIdRouteImport.update({
    id: '/forms/$activityId/$templateId',
    path: '/forms/$activityId/$templateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTripsTripIdRoute =
  AuthenticatedTripsTripIdRouteImport.update({
    id: '/$tripId',
    path: '/$tripId',
    getParentRoute: () => AuthenticatedTripsRoute,
  } as any)
const AuthenticatedSchoolsSchoolIdRoute =
  AuthenticatedSchoolsSchoolIdRouteImport.update({
    id: '/schools/$schoolId',
    path: '/schools/$schoolId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentsAgentIdRoute =
  AuthenticatedAgentsAgentIdRouteImport.update({
    id: '/$agentId',
    path: '/$agentId',
    getParentRoute: () => AuthenticatedAgentsRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPlanningRemindersRoute =
  ApiPublicPlanningRemindersRouteImport.update({
    id: '/api/public/planning/reminders',
    path: '/api/public/planning/reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTripsTripIdReportRoute =
  AuthenticatedTripsTripIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => AuthenticatedTripsTripIdRoute,
  } as any)
const AuthenticatedTripsTripIdActivitiesActivityIdRoute =
  AuthenticatedTripsTripIdActivitiesActivityIdRouteImport.update({
    id: '/activities/$activityId',
    path: '/activities/$activityId',
    getParentRoute: () => AuthenticatedTripsTripIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/forms': typeof AuthenticatedFormsRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/planning': typeof AuthenticatedPlanningRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/trips': typeof AuthenticatedTripsRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/f/$instanceId': typeof FInstanceIdRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/schools/$schoolId': typeof AuthenticatedSchoolsSchoolIdRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRouteWithChildren
  '/forms/$activityId/$templateId': typeof FormsActivityIdTemplateIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/public/intake/$type': typeof PublicIntakeTypeRoute
  '/agents/': typeof AuthenticatedAgentsIndexRoute
  '/schools/': typeof AuthenticatedSchoolsIndexRoute
  '/trips/': typeof AuthenticatedTripsIndexRoute
  '/trips/$tripId/report': typeof AuthenticatedTripsTripIdReportRoute
  '/api/public/planning/reminders': typeof ApiPublicPlanningRemindersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/trips/$tripId/activities/$activityId': typeof AuthenticatedTripsTripIdActivitiesActivityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/forms': typeof AuthenticatedFormsRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/planning': typeof AuthenticatedPlanningRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/users': typeof AuthenticatedUsersRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/f/$instanceId': typeof FInstanceIdRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/schools/$schoolId': typeof AuthenticatedSchoolsSchoolIdRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRouteWithChildren
  '/forms/$activityId/$templateId': typeof FormsActivityIdTemplateIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/public/intake/$type': typeof PublicIntakeTypeRoute
  '/agents': typeof AuthenticatedAgentsIndexRoute
  '/schools': typeof AuthenticatedSchoolsIndexRoute
  '/trips': typeof AuthenticatedTripsIndexRoute
  '/trips/$tripId/report': typeof AuthenticatedTripsTripIdReportRoute
  '/api/public/planning/reminders': typeof ApiPublicPlanningRemindersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/trips/$tripId/activities/$activityId': typeof AuthenticatedTripsTripIdActivitiesActivityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/forms': typeof AuthenticatedFormsRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/planning': typeof AuthenticatedPlanningRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/trips': typeof AuthenticatedTripsRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/f/$instanceId': typeof FInstanceIdRoute
  '/_authenticated/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/_authenticated/schools/$schoolId': typeof AuthenticatedSchoolsSchoolIdRoute
  '/_authenticated/trips/$tripId': typeof AuthenticatedTripsTripIdRouteWithChildren
  '/forms/$activityId/$templateId': typeof FormsActivityIdTemplateIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/public/intake/$type': typeof PublicIntakeTypeRoute
  '/_authenticated/agents/': typeof AuthenticatedAgentsIndexRoute
  '/_authenticated/schools/': typeof AuthenticatedSchoolsIndexRoute
  '/_authenticated/trips/': typeof AuthenticatedTripsIndexRoute
  '/_authenticated/trips/$tripId/report': typeof AuthenticatedTripsTripIdReportRoute
  '/api/public/planning/reminders': typeof ApiPublicPlanningRemindersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/trips/$tripId/activities/$activityId': typeof AuthenticatedTripsTripIdActivitiesActivityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/unsubscribe'
    | '/agents'
    | '/dashboard'
    | '/forms'
    | '/inbox'
    | '/planning'
    | '/reports'
    | '/settings'
    | '/templates'
    | '/trips'
    | '/users'
    | '/email/unsubscribe'
    | '/f/$instanceId'
    | '/agents/$agentId'
    | '/schools/$schoolId'
    | '/trips/$tripId'
    | '/forms/$activityId/$templateId'
    | '/lovable/email/suppression'
    | '/public/intake/$type'
    | '/agents/'
    | '/schools/'
    | '/trips/'
    | '/trips/$tripId/report'
    | '/api/public/planning/reminders'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/trips/$tripId/activities/$activityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/unsubscribe'
    | '/dashboard'
    | '/forms'
    | '/inbox'
    | '/planning'
    | '/reports'
    | '/settings'
    | '/templates'
    | '/users'
    | '/email/unsubscribe'
    | '/f/$instanceId'
    | '/agents/$agentId'
    | '/schools/$schoolId'
    | '/trips/$tripId'
    | '/forms/$activityId/$templateId'
    | '/lovable/email/suppression'
    | '/public/intake/$type'
    | '/agents'
    | '/schools'
    | '/trips'
    | '/trips/$tripId/report'
    | '/api/public/planning/reminders'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/trips/$tripId/activities/$activityId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/unsubscribe'
    | '/_authenticated/agents'
    | '/_authenticated/dashboard'
    | '/_authenticated/forms'
    | '/_authenticated/inbox'
    | '/_authenticated/planning'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/templates'
    | '/_authenticated/trips'
    | '/_authenticated/users'
    | '/email/unsubscribe'
    | '/f/$instanceId'
    | '/_authenticated/agents/$agentId'
    | '/_authenticated/schools/$schoolId'
    | '/_authenticated/trips/$tripId'
    | '/forms/$activityId/$templateId'
    | '/lovable/email/suppression'
    | '/public/intake/$type'
    | '/_authenticated/agents/'
    | '/_authenticated/schools/'
    | '/_authenticated/trips/'
    | '/_authenticated/trips/$tripId/report'
    | '/api/public/planning/reminders'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/trips/$tripId/activities/$activityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  FInstanceIdRoute: typeof FInstanceIdRoute
  FormsActivityIdTemplateIdRoute: typeof FormsActivityIdTemplateIdRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  PublicIntakeTypeRoute: typeof PublicIntakeTypeRoute
  ApiPublicPlanningRemindersRoute: typeof ApiPublicPlanningRemindersRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$instanceId': {
      id: '/f/$instanceId'
      path: '/f/$instanceId'
      fullPath: '/f/$instanceId'
      preLoaderRoute: typeof FInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trips': {
      id: '/_authenticated/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AuthenticatedTripsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planning': {
      id: '/_authenticated/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof AuthenticatedPlanningRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forms': {
      id: '/_authenticated/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AuthenticatedFormsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trips/': {
      id: '/_authenticated/trips/'
      path: '/'
      fullPath: '/trips/'
      preLoaderRoute: typeof AuthenticatedTripsIndexRouteImport
      parentRoute: typeof AuthenticatedTripsRoute
    }
    '/_authenticated/schools/': {
      id: '/_authenticated/schools/'
      path: '/schools'
      fullPath: '/schools/'
      preLoaderRoute: typeof AuthenticatedSchoolsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents/': {
      id: '/_authenticated/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthenticatedAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedAgentsRoute
    }
    '/public/intake/$type': {
      id: '/public/intake/$type'
      path: '/public/intake/$type'
      fullPath: '/public/intake/$type'
      preLoaderRoute: typeof PublicIntakeTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$activityId/$templateId': {
      id: '/forms/$activityId/$templateId'
      path: '/forms/$activityId/$templateId'
      fullPath: '/forms/$activityId/$templateId'
      preLoaderRoute: typeof FormsActivityIdTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trips/$tripId': {
      id: '/_authenticated/trips/$tripId'
      path: '/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof AuthenticatedTripsTripIdRouteImport
      parentRoute: typeof AuthenticatedTripsRoute
    }
    '/_authenticated/schools/$schoolId': {
      id: '/_authenticated/schools/$schoolId'
      path: '/schools/$schoolId'
      fullPath: '/schools/$schoolId'
      preLoaderRoute: typeof AuthenticatedSchoolsSchoolIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents/$agentId': {
      id: '/_authenticated/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedAgentsRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/planning/reminders': {
      id: '/api/public/planning/reminders'
      path: '/api/public/planning/reminders'
      fullPath: '/api/public/planning/reminders'
      preLoaderRoute: typeof ApiPublicPlanningRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trips/$tripId/report': {
      id: '/_authenticated/trips/$tripId/report'
      path: '/report'
      fullPath: '/trips/$tripId/report'
      preLoaderRoute: typeof AuthenticatedTripsTripIdReportRouteImport
      parentRoute: typeof AuthenticatedTripsTripIdRoute
    }
    '/_authenticated/trips/$tripId/activities/$activityId': {
      id: '/_authenticated/trips/$tripId/activities/$activityId'
      path: '/activities/$activityId'
      fullPath: '/trips/$tripId/activities/$activityId'
      preLoaderRoute: typeof AuthenticatedTripsTripIdActivitiesActivityIdRouteImport
      parentRoute: typeof AuthenticatedTripsTripIdRoute
    }
  }
}

interface AuthenticatedAgentsRouteChildren {
  AuthenticatedAgentsAgentIdRoute: typeof AuthenticatedAgentsAgentIdRoute
  AuthenticatedAgentsIndexRoute: typeof AuthenticatedAgentsIndexRoute
}

const AuthenticatedAgentsRouteChildren: AuthenticatedAgentsRouteChildren = {
  AuthenticatedAgentsAgentIdRoute: AuthenticatedAgentsAgentIdRoute,
  AuthenticatedAgentsIndexRoute: AuthenticatedAgentsIndexRoute,
}

const AuthenticatedAgentsRouteWithChildren =
  AuthenticatedAgentsRoute._addFileChildren(AuthenticatedAgentsRouteChildren)

interface AuthenticatedTripsTripIdRouteChildren {
  AuthenticatedTripsTripIdReportRoute: typeof AuthenticatedTripsTripIdReportRoute
  AuthenticatedTripsTripIdActivitiesActivityIdRoute: typeof AuthenticatedTripsTripIdActivitiesActivityIdRoute
}

const AuthenticatedTripsTripIdRouteChildren: AuthenticatedTripsTripIdRouteChildren =
  {
    AuthenticatedTripsTripIdReportRoute: AuthenticatedTripsTripIdReportRoute,
    AuthenticatedTripsTripIdActivitiesActivityIdRoute:
      AuthenticatedTripsTripIdActivitiesActivityIdRoute,
  }

const AuthenticatedTripsTripIdRouteWithChildren =
  AuthenticatedTripsTripIdRoute._addFileChildren(
    AuthenticatedTripsTripIdRouteChildren,
  )

interface AuthenticatedTripsRouteChildren {
  AuthenticatedTripsTripIdRoute: typeof AuthenticatedTripsTripIdRouteWithChildren
  AuthenticatedTripsIndexRoute: typeof AuthenticatedTripsIndexRoute
}

const AuthenticatedTripsRouteChildren: AuthenticatedTripsRouteChildren = {
  AuthenticatedTripsTripIdRoute: AuthenticatedTripsTripIdRouteWithChildren,
  AuthenticatedTripsIndexRoute: AuthenticatedTripsIndexRoute,
}

const AuthenticatedTripsRouteWithChildren =
  AuthenticatedTripsRoute._addFileChildren(AuthenticatedTripsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFormsRoute: typeof AuthenticatedFormsRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedPlanningRoute: typeof AuthenticatedPlanningRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedTripsRoute: typeof AuthenticatedTripsRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedSchoolsSchoolIdRoute: typeof AuthenticatedSchoolsSchoolIdRoute
  AuthenticatedSchoolsIndexRoute: typeof AuthenticatedSchoolsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFormsRoute: AuthenticatedFormsRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedPlanningRoute: AuthenticatedPlanningRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedTripsRoute: AuthenticatedTripsRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedSchoolsSchoolIdRoute: AuthenticatedSchoolsSchoolIdRoute,
  AuthenticatedSchoolsIndexRoute: AuthenticatedSchoolsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  FInstanceIdRoute: FInstanceIdRoute,
  FormsActivityIdTemplateIdRoute: FormsActivityIdTemplateIdRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  PublicIntakeTypeRoute: PublicIntakeTypeRoute,
  ApiPublicPlanningRemindersRoute: ApiPublicPlanningRemindersRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
