/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTripsRouteImport } from './routes/_authenticated.trips'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated.templates'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedSchoolsRouteImport } from './routes/_authenticated.schools'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedFormsRouteImport } from './routes/_authenticated.forms'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated.agents'
import { Route as FormsActivityIdTemplateIdRouteImport } from './routes/forms.$activityId.$templateId'
import { Route as AuthenticatedTripsTripIdRouteImport } from './routes/_authenticated.trips.$tripId'
import { Route as AuthenticatedAgentsAgentIdRouteImport } from './routes/_authenticated.agents.$agentId'
import { Route as AuthenticatedTripsTripIdReportRouteImport } from './routes/_authenticated.trips.$tripId.report'
import { Route as AuthenticatedTripsTripIdActivitiesActivityIdRouteImport } from './routes/_authenticated.trips.$tripId.activities.$activityId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTripsRoute = AuthenticatedTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSchoolsRoute = AuthenticatedSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFormsRoute = AuthenticatedFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const FormsActivityIdTemplateIdRoute =
  FormsActivityIdTemplateIdRouteImport.update({
    id: '/forms/$activityId/$templateId',
    path: '/forms/$activityId/$templateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTripsTripIdRoute =
  AuthenticatedTripsTripIdRouteImport.update({
    id: '/$tripId',
    path: '/$tripId',
    getParentRoute: () => AuthenticatedTripsRoute,
  } as any)
const AuthenticatedAgentsAgentIdRoute =
  AuthenticatedAgentsAgentIdRouteImport.update({
    id: '/$agentId',
    path: '/$agentId',
    getParentRoute: () => AuthenticatedAgentsRoute,
  } as any)
const AuthenticatedTripsTripIdReportRoute =
  AuthenticatedTripsTripIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => AuthenticatedTripsTripIdRoute,
  } as any)
const AuthenticatedTripsTripIdActivitiesActivityIdRoute =
  AuthenticatedTripsTripIdActivitiesActivityIdRouteImport.update({
    id: '/activities/$activityId',
    path: '/activities/$activityId',
    getParentRoute: () => AuthenticatedTripsTripIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/forms': typeof AuthenticatedFormsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/schools': typeof AuthenticatedSchoolsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/trips': typeof AuthenticatedTripsRouteWithChildren
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRouteWithChildren
  '/forms/$activityId/$templateId': typeof FormsActivityIdTemplateIdRoute
  '/trips/$tripId/report': typeof AuthenticatedTripsTripIdReportRoute
  '/trips/$tripId/activities/$activityId': typeof AuthenticatedTripsTripIdActivitiesActivityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/forms': typeof AuthenticatedFormsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/schools': typeof AuthenticatedSchoolsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/trips': typeof AuthenticatedTripsRouteWithChildren
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRouteWithChildren
  '/forms/$activityId/$templateId': typeof FormsActivityIdTemplateIdRoute
  '/trips/$tripId/report': typeof AuthenticatedTripsTripIdReportRoute
  '/trips/$tripId/activities/$activityId': typeof AuthenticatedTripsTripIdActivitiesActivityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/forms': typeof AuthenticatedFormsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/schools': typeof AuthenticatedSchoolsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/trips': typeof AuthenticatedTripsRouteWithChildren
  '/_authenticated/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/_authenticated/trips/$tripId': typeof AuthenticatedTripsTripIdRouteWithChildren
  '/forms/$activityId/$templateId': typeof FormsActivityIdTemplateIdRoute
  '/_authenticated/trips/$tripId/report': typeof AuthenticatedTripsTripIdReportRoute
  '/_authenticated/trips/$tripId/activities/$activityId': typeof AuthenticatedTripsTripIdActivitiesActivityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agents'
    | '/dashboard'
    | '/forms'
    | '/reports'
    | '/schools'
    | '/settings'
    | '/templates'
    | '/trips'
    | '/agents/$agentId'
    | '/trips/$tripId'
    | '/forms/$activityId/$templateId'
    | '/trips/$tripId/report'
    | '/trips/$tripId/activities/$activityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agents'
    | '/dashboard'
    | '/forms'
    | '/reports'
    | '/schools'
    | '/settings'
    | '/templates'
    | '/trips'
    | '/agents/$agentId'
    | '/trips/$tripId'
    | '/forms/$activityId/$templateId'
    | '/trips/$tripId/report'
    | '/trips/$tripId/activities/$activityId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agents'
    | '/_authenticated/dashboard'
    | '/_authenticated/forms'
    | '/_authenticated/reports'
    | '/_authenticated/schools'
    | '/_authenticated/settings'
    | '/_authenticated/templates'
    | '/_authenticated/trips'
    | '/_authenticated/agents/$agentId'
    | '/_authenticated/trips/$tripId'
    | '/forms/$activityId/$templateId'
    | '/_authenticated/trips/$tripId/report'
    | '/_authenticated/trips/$tripId/activities/$activityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  FormsActivityIdTemplateIdRoute: typeof FormsActivityIdTemplateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trips': {
      id: '/_authenticated/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AuthenticatedTripsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schools': {
      id: '/_authenticated/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof AuthenticatedSchoolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forms': {
      id: '/_authenticated/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AuthenticatedFormsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/forms/$activityId/$templateId': {
      id: '/forms/$activityId/$templateId'
      path: '/forms/$activityId/$templateId'
      fullPath: '/forms/$activityId/$templateId'
      preLoaderRoute: typeof FormsActivityIdTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trips/$tripId': {
      id: '/_authenticated/trips/$tripId'
      path: '/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof AuthenticatedTripsTripIdRouteImport
      parentRoute: typeof AuthenticatedTripsRoute
    }
    '/_authenticated/agents/$agentId': {
      id: '/_authenticated/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedAgentsRoute
    }
    '/_authenticated/trips/$tripId/report': {
      id: '/_authenticated/trips/$tripId/report'
      path: '/report'
      fullPath: '/trips/$tripId/report'
      preLoaderRoute: typeof AuthenticatedTripsTripIdReportRouteImport
      parentRoute: typeof AuthenticatedTripsTripIdRoute
    }
    '/_authenticated/trips/$tripId/activities/$activityId': {
      id: '/_authenticated/trips/$tripId/activities/$activityId'
      path: '/activities/$activityId'
      fullPath: '/trips/$tripId/activities/$activityId'
      preLoaderRoute: typeof AuthenticatedTripsTripIdActivitiesActivityIdRouteImport
      parentRoute: typeof AuthenticatedTripsTripIdRoute
    }
  }
}

interface AuthenticatedAgentsRouteChildren {
  AuthenticatedAgentsAgentIdRoute: typeof AuthenticatedAgentsAgentIdRoute
}

const AuthenticatedAgentsRouteChildren: AuthenticatedAgentsRouteChildren = {
  AuthenticatedAgentsAgentIdRoute: AuthenticatedAgentsAgentIdRoute,
}

const AuthenticatedAgentsRouteWithChildren =
  AuthenticatedAgentsRoute._addFileChildren(AuthenticatedAgentsRouteChildren)

interface AuthenticatedTripsTripIdRouteChildren {
  AuthenticatedTripsTripIdReportRoute: typeof AuthenticatedTripsTripIdReportRoute
  AuthenticatedTripsTripIdActivitiesActivityIdRoute: typeof AuthenticatedTripsTripIdActivitiesActivityIdRoute
}

const AuthenticatedTripsTripIdRouteChildren: AuthenticatedTripsTripIdRouteChildren =
  {
    AuthenticatedTripsTripIdReportRoute: AuthenticatedTripsTripIdReportRoute,
    AuthenticatedTripsTripIdActivitiesActivityIdRoute:
      AuthenticatedTripsTripIdActivitiesActivityIdRoute,
  }

const AuthenticatedTripsTripIdRouteWithChildren =
  AuthenticatedTripsTripIdRoute._addFileChildren(
    AuthenticatedTripsTripIdRouteChildren,
  )

interface AuthenticatedTripsRouteChildren {
  AuthenticatedTripsTripIdRoute: typeof AuthenticatedTripsTripIdRouteWithChildren
}

const AuthenticatedTripsRouteChildren: AuthenticatedTripsRouteChildren = {
  AuthenticatedTripsTripIdRoute: AuthenticatedTripsTripIdRouteWithChildren,
}

const AuthenticatedTripsRouteWithChildren =
  AuthenticatedTripsRoute._addFileChildren(AuthenticatedTripsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFormsRoute: typeof AuthenticatedFormsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSchoolsRoute: typeof AuthenticatedSchoolsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedTripsRoute: typeof AuthenticatedTripsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFormsRoute: AuthenticatedFormsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSchoolsRoute: AuthenticatedSchoolsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedTripsRoute: AuthenticatedTripsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  FormsActivityIdTemplateIdRoute: FormsActivityIdTemplateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
